services:
  postgres:
    container_name: template_nextjs_postgres
    image: postgres:18
    ports:
      - "25271:5432"
    volumes:
      - postgres:/var/lib/postgresql
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=main

  #valkey:
  #  image: valkey:latest
  #  container_name: template_nextjs_valkey
  #  ports:
  #    - "41013:6379"
  #  volumes:
  #    - valkey-data:/data

volumes:
  postgres:
    driver: local
  #valkey-data:
  #  driver: local
