// This file is auto-generated by @hey-api/openapi-ts

import type { UseMutationOptions } from "@tanstack/react-query"

import { deleteApiV1UserMeDelete, type Options } from "../sdk.gen"
import type {
  DeleteApiV1UserMeDeleteData,
  DeleteApiV1UserMeDeleteError,
  DeleteApiV1UserMeDeleteResponse,
} from "../types.gen"

export const deleteApiV1UserMeDeleteMutation = (
  options?: Partial<Options<DeleteApiV1UserMeDeleteData>>,
): UseMutationOptions<
  DeleteApiV1UserMeDeleteResponse,
  DeleteApiV1UserMeDeleteError,
  Options<DeleteApiV1UserMeDeleteData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteApiV1UserMeDeleteResponse,
    DeleteApiV1UserMeDeleteError,
    Options<DeleteApiV1UserMeDeleteData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteApiV1UserMeDelete({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}
